blank_issues_enabled: false
contact_links:
  - name: Discord Community Support
    url: discord.gg/MFQnYm2f2d
    about: Join our official Discord server for real-time help, announcements, and quick questions.
  - name: Bot Wiki / Documentation
    url: https://github.com/777-Steam-Gem-Tf2key-Bot/wiki
    about: Please check the Wiki first—your question may already be answered there.
