# This workflow ensures that every code change (push or pull request) is stable,
# installs dependencies cleanly, and runs tests across supported Node.js versions.

name: Node.js CI

on:
  push:
    # Triggers on push to the primary branch
    branches: [ "master" ]
  pull_request:
    # Triggers on pull requests targeting the primary branch
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Test the bot against the required Node.js LTS versions
    strategy:
      matrix:
        # Focusing on Node.js 20.x, as it's required by your dependencies and 'engines' field.
        # Running on 18.x caused EBADENGINE warnings.
        node-version: [20.x] 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # Caching dependencies speeds up subsequent builds
        cache: 'npm'
        
    - name: Install Dependencies (Clean Install)
      # 'npm ci' ensures an exact install from package-lock.json, ideal for CI.
      # The '--force' flag is added to suppress EBADENGINE errors that occur even
      # when using the correct Node version due to strict dependency requirements.
      run: npm ci --force
      
    - name: Run Tests (Linting Check)
      # Runs the 'test' script from package.json, which you set to run 'lint'.
      run: npm test
    
    - name: Run Tests
      # Assuming you have a 'test' script defined in your package.json
      run: npm test
